title: Valinor Earth’s Blog

remote_theme: oinam/oinam-jekyll

markdown: kramdown
highlighter: rouge
future: false
show_drafts: false

permalink: pretty
permalink: /:title/

feed:
  posts_limit: 10
  author: Valinor.Earth

layout:
  theme: default
  home_posts_no: 10
  posts_home: /
  link_new_tab: false # should external links open in a new tab (true) or in the current tab (false)

styles:
  font_family: serif

plugins:
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-titles-from-headings
  
optional_front_matter:
  remove_originals: true

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

defaults:
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/:year/:title/'

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - _drafts
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - README.*